### ISSUE TITLE
moment-with-locales.min.js.map not loading on pbs92 clock

### ISSUE THREAD

**Issue by NosillaCast** [bartificer/programming-by-stealth#10]
On your clock solution to the PBS 92 challenge, the library you're calling on cloudflare isn't there (404).

![image](https://user-images.githubusercontent.com/12651464/82564800-3d737880-9b2e-11ea-913d-c2c97e1c55b6.png)

**Comment by bbusschots** [comment]
This is just the optional MAP file, not the library itself. Not an issue.
