### ISSUE TITLE
All URL titles have "join the community" attached to them

### ISSUE THREAD

**Issue by NosillaCast** [bartificer/programming-by-stealth#11]
Example from doing a Google search:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/12651464/89368659-f0189900-d690-11ea-84a7-ab1c5a08f76f.png">

What browser tabs look like:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/12651464/89368688-fe66b500-d690-11ea-8bb7-7d5c0c3a7460.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/12651464/89368756-2524eb80-d691-11ea-9c2e-13df4ad48951.png">

**Comment by hepabolu** [comment]
A little research
- Google search: 'pbs bartificer'
- the text in the Google results is the text in the <html><head><title> tag
- this header is added by the Jekyll theme

aka should be fixed in the theme

**Comment by NosillaCast** [comment]
It looks like at some point @bartificer fixed this.
