### ISSUE TITLE
PBS78  Is it really data-toggler="popover"?

### ISSUE THREAD

**Issue by NosillaCast** [bartificer/programming-by-stealth#21]
I was reviewing the installment on popovers right after having read the Bootstrap documentation, and noticed that @bartificer writes:

`data-toggler="popover"`

But the documentation at https://getbootstrap.com/docs/4.3/components/popovers/ writes it:

`data-toggle="popover"`

Is it really toggler? I can't find any reference on the Internet to it spelled that way.

**Comment by bbusschots** [comment]
Looks like you found a typo.

**Comment by NosillaCast** [comment]
Crazy - our browsers must just be so lenient they let it go, because it definitely worked with toggler. Fixed now.
