### ISSUE TITLE
Next link not auto-generating

### ISSUE THREAD

**Issue by podfeet** [bartificer/programming-by-stealth#39]
PBS159 has been published but PBS158 doesn't show a link to it at the bottom.

**Comment by helmavdl** [comment]
I cannot reproduce the problem. When running the script it correctly updates pbs158.md and pbs159.md.

**Comment by podfeet** [comment]
I can see that PBS158 now shows PBS159 at the bottom, but it did not until you manually ran the script. Somehow the script did not run when we pushed PBS159 to the repo.

**Comment by SteveMattan** [comment]
Also note that PBS 159 does not have a forward link to PBS 160, and PBS 160 and 161 have no links.
