### ISSUE TITLE
PBS 145 Incomplete Sentence

### ISSUE THREAD

**Issue by SteveMattan** [bartificer/programming-by-stealth#44]
In PBS 145, section "Other Useful Operators" it reads:

`Other Useful Operators
There’s one other unary operator I think is worth mentioning, -v checks if a variable with the given exists (has a value).`

... with the given WHAT exists?

Perhaps name?

**Comment by podfeet** [comment]
Leaving this one for @bbusschots. I have no idea!

**Comment by bbusschots** [comment]
Re-worded for more clarity.
