### ISSUE TITLE
PBS 110 Missing Link

### ISSUE THREAD

**Issue by SteveMattan** [bartificer/programming-by-stealth#46]
In PBS 110, at the end of the show notes, there is a section entitled, "Palate Cleaner" which references, but does not include, a link to a TikTok video. As discussed in an email exchange with Allison, she will either add the link or remove the section.

**Comment by podfeet** [comment]
This might sound like a small thing to spend so much hunting down, but it was a video by Scott Hanselman, CEO of Learning to CODE, and VP at Microsoft DevDiv about imposter syndrome. I found it and fixed it!
