### ISSUE TITLE
PBS 157 mixup with select() and any()

### ISSUE THREAD

**Issue by libjack** [bartificer/programming-by-stealth#47]
In the final paragraph, right before the challenges:

> We are now calling the select function just once for each Nobel prize in the dataset. When we call it, we pass the filter .laureates[]? as the generator, which will explode the array of winners into separate values, each of those values is then tested against the second argument to select, the filter .surname == "Curie", to produce one boolean for each laureate depending on whether or not their surname matched. If any one surname matches, then the entire input to the select function is returned, i.e., the entire prize, not just the laureate.

I believe it refers to select() when it should be referring to any(), e.g. where describing the arguments to any(), describing the generator and then the filter is mentioned as `the second argument to select()`

**Comment by podfeet** [comment]
I'll leave this one to bbusschots

**Comment by bbusschots** [comment]
Thanks @libjack — that whole paragraph needed to be re-written to keep everything clear. Done and committed as https://github.com/bartificer/programming-by-stealth/commit/22b4bd95f1f1d85ae2775143e9b240fa84b148a2

**Comment by SteveMattan** [comment]
@bbusschots, @podfeet should this issue be closed then?

**Comment by podfeet** [comment]
Yes - thanks @SteveMattan!
