### ISSUE TITLE
PBS 134 Markdown Issue?

### ISSUE THREAD

**Issue by SteveMattan** [bartificer/programming-by-stealth#52]
In the show notes, in the 'Pass-through' Functions in Chains section, the Note at the end of the section is written as follows:

\*__Note:__ if your JavaScript console also writes returned values to the console, then the final \*'caaaaw'* will be followed by the value returned by the final call to the `.squawk()` function, i.e. and instance of the `Parrot` class with the name Polly.*

Notice the "*" around "caaaaw". In the Show notes markdown these do not seem to have any effect. I both Safari and Firefox, the text up through "caaaaw" is in italic, and the subsequent text is not italic. 

This is the text from Safari (note the "*" prior to "'caaaaw'" and at the end of the sentence):

_Note: if your JavaScript console also writes returned values to the console, then the final *‘caaaaw’_ will be followed by the value returned by the final call to the .squawk() function, i.e. and instance of the Parrot class with the name Polly.*

As the expected purpose of the asterisks bracketing 'caaaaw' is not obvious, it is not clear what correction might be needed.

**Comment by podfeet** [comment]
That was an interesting one. The "Note" syntax formats automatically as italics, so when Bart added italics on 'caaaw', it removed the italics using the first asterisk. I've simply removed the superfluous italics notation.
