### ISSUE TITLE
Some recent PBS HTML pages show "Join the Community" in the tab title.

### ISSUE THREAD

**Issue by macLurker** [bartificer/programming-by-stealth#56]
The following PBS module pages show "Join the Community" in the tab title: PBS161, PBS162, PBS163, PBS165, PBS166, and PBS167. I checked PBS150 to PBS167. All the others I checked correctly show "PBS x of X - <title text>" in the tab title. 

I compared the HTML source for the good files & the bad files. The ones that work have a top-level header "h1" with the module info. The ones that don't work have level 2 "h2". I'm not sure if that's related, but it's a place to start.

I often have multiple PBS pages open at one time. Not having the module number in the tab title makes getting the page I want difficult since they all look the same. I have to click on the tab to see if it's the page I want at the moment. Very annoying. So please fix. Thanks.

**Comment by podfeet** [comment]
If that is actually the root cause, I can easily fix it. Please identify the pages that have the problem.

**Comment by macLurker** [comment]
The following PBS module pages show "Join the Community" in the tab title: 
PBS161, 
PBS162, 
PBS163, 
PBS165, 
PBS166,
 and PBS167. 

I only checked PBS150 to PBS167. But it's a recent problem. There doesn't seem to be a way to do a group search.

**Comment by podfeet** [comment]
Confirmed that was the problem. I just changed PBS 161's first line to be H1 and now the title shows in the tab bar. I'm going to leave this open until I fix all that you've noted. I'll also talk to @bartificer about fixing the the template he uses for the shownotes. 

Thanks @macLurker!

**Comment by podfeet** [comment]
All installments past PBS 160 now start with an H1 tag so their tabs now show the title of the episode. I clicked every installment up to and including 160 to ensure they were all presenting correctly.
