### ISSUE TITLE
PBS135 line 130: invalid json?

### ISSUE THREAD

**Issue by hepabolu** [bartificer/programming-by-stealth#59]
## Content

```json
{
  "name": "pbs135a-joiner",
........
  "keywords": [
    "JavaScript",
    "Jest",
    "Programming",
    "by",
    "Stealth",
    "Example"
  ],
  "author": "Bart Busschots",
  "license": "ISC",
  x
}
```

## Issue

the last 'x' is invalid JSON. Further investigation shows the change in 13cff00

## Question

Is this intentional or an accident?

**Comment by bbusschots** [comment]
This appears to have been fixed by someone already, because the current published version does not have the silly stray x
